export const preferenceCategoryOptions = [
  {
    value: 'wildfire',
    label: 'Wildfires',
    description: 'Fire spread, smoke movement, evacuations, and utility shutoffs.',
  },
  {
    value: 'storm-weather',
    label: 'Storms & Weather',
    description: 'Typhoons, floods, heavy rain, extreme weather, and coastal disruptions.',
  },
  {
    value: 'earthquake',
    label: 'Earthquakes',
    description: 'Seismic shocks, aftershocks, structural damage, and response activity.',
  },
  {
    value: 'protest',
    label: 'Civil Unrest',
    description: 'Protests, demonstrations, strikes, and street-level disruption.',
  },
  {
    value: 'transit',
    label: 'Transit & Infrastructure',
    description: 'Rail, road, aviation, and mobility constraints that change daily operations.',
  },
  {
    value: 'port-markets',
    label: 'Ports & Markets',
    description: 'Port incidents, shipping friction, supply-chain drag, and market-sensitive moves.',
  },
  {
    value: 'other',
    label: 'Other Signals',
    description: 'Broader developments that do not fit the main coverage groups.',
  },
]

export const preferenceCountryOptions = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  "Cote d'Ivoire",
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Republic of the Congo',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]

export function normalizeEventCategory(category = '') {
  const normalized = category.toLowerCase()

  if (normalized === 'weather' || normalized === 'storm') return 'storm-weather'
  if (normalized === 'market' || normalized === 'port') return 'port-markets'
  if (normalized === 'wildfire') return 'wildfire'
  if (normalized === 'earthquake') return 'earthquake'
  if (normalized === 'protest') return 'protest'
  if (normalized === 'transit') return 'transit'

  return 'other'
}

export function getPreferenceCategoryLabel(value) {
  return preferenceCategoryOptions.find((option) => option.value === value)?.label ?? 'Other Signals'
}

export function getEventCountryLabel(event) {
  if (event?.country) return event.country

  const parts = event?.location?.split(',') ?? []
  return parts.length ? parts[parts.length - 1].trim() : 'Unknown'
}
